services:
  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: giapha
      POSTGRES_PASSWORD: giapha
      POSTGRES_DB: giapha
    volumes:
      - ./.docker/postgres/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U giapha"]
      interval: 5s
      timeout: 5s
      retries: 5

  garage:
    image: dxflrs/garage:v1.1.0
    ports:
      - "3900:3900"
      - "3902:3902"
      - "3903:3903"
    volumes:
      - ./.docker/garage/data:/var/lib/garage
      - ./.docker/garage/garage.toml:/etc/garage.toml

volumes:
  postgres_data:
  garage_data:
